name: developer11
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  percent_indicator: ^4.0.0
  dependencies:
  font_awesome_flutter: ^9.2.0
  url_launcher: ^6.0.18
  progress_state_button: ^1.0.4
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true


  assets:
    - images/

  fonts:
  - family: Poppin
    fonts:
    - asset: fonts/Poppins-Black.ttf
    - asset: fonts/Poppins-BlackItalic.ttf
    - asset: fonts/Poppins-Bold.ttf
    - asset: fonts/Poppins-BoldItalic.ttf
    - asset: fonts/Poppins-ExtraBold.ttf
    - asset: fonts/Poppins-ExtraBoldItalic.ttf
    - asset: fonts/Poppins-ExtraLight.ttf
    - asset: fonts/Poppins-ExtraLightItalic.ttf
    - asset: fonts/Poppins-Italic.ttf
    - asset: fonts/Poppins-Light.ttf
    - asset: fonts/Poppins-LightItalic.ttf
    - asset: fonts/Poppins-Medium.ttf
    - asset: fonts/Poppins-MediumItalic.ttf
    - asset: fonts/Poppins-Regular.ttf
    - asset: fonts/Poppins-SemiBold.ttf
    - asset: fonts/Poppins-SemiBoldItalic.ttf
    - asset: fonts/Poppins-Thin.ttf
    - asset: fonts/Poppins-ThinItalic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
